//! Repository layer — async sqlx queries against SQLite.
//!
//! Each sub-module owns one entity (notes, recordings, transcripts) and
//! exposes typed CRUD helpers used by `crate::commands::*`. No domain logic
//! lives here — pure data access.
//!
//! Patterns:
//! - All IDs generated by repo at create-time (UUID v4 string).
//! - All timestamps default to `datetime('now')` via SQL default.
//! - `not found` → `Error::NotFound` (deterministic mapping).
//! - For long-running tasks the task-spawning code uses the G-TASK-001 single-
//!   commit pattern: pre-generate task_id, insert row with status=processing +
//!   task_id in one transaction, then spawn. Implementations live in
//!   `recordings` / `transcripts` next to where they are dispatched.

pub mod ai_endpoints;
pub mod chat;
pub mod note_bodies;
pub mod notes;
pub mod recordings;
pub mod settings;
pub mod tags;
pub mod transcripts;
